[target.thumbv7em-none-eabihf]
runner = "arm-none-eabi-gdb -q --command=openocd.gdbinit"
rustflags = [
  "-C", "link-arg=-Tlink.x",
#  "-C", "link-arg=-nostartfiles",
]

[build]
target = "thumbv7em-none-eabihf"